coverage:
  precision: 2
  round: nearest
  range: "70...100"
  status:
    project:
      default:
         target: 30%
codecov:
  notify:
    require_ci_to_pass: yes
comment:         
  layout: "header, diff"
  behaviour: default
  require_changes: no
