language: java
install: true
jdk:
  - oraclejdk8
script:
#  - mvn clean package
  - mvn clean org.jacoco:jacoco-maven-plugin:prepare-agent
cache:
  directories:
  - '$HOME/.m2/repository'
# blocklist
branches:
  except:
  - test