language: java
install: true
jdk:
  - oraclejdk8
addons:
  sonarcloud:
    organization: "xylene1980-github"
    token:
      secure: $SONAR_TOKEN
script:
#  - mvn clean package
  - mvn clean org.jacoco:jacoco-maven-plugin:prepare-agent install sonar:sonar
  - mvn cobertura:cobertura
cache:
  directories:
  - '$HOME/.m2/repository'
# blocklist
branches:
  except:
  - test
after_success:
  - bash <(curl -s https://codecov.io/bash)