language: java
install: true
jdk:
  - oraclejdk8
script:
#  - mvn clean package
  - mvn clean org.jacoco:jacoco-maven-plugin:prepare-agent
  - mvn cobertura:cobertura
cache:
  directories:
  - '$HOME/.m2/repository'
# blocklist
branches:
  except:
  - test
after_success:
  - bash <(curl -s https://codecov.io/bash)